# Generated by Django 3.2.8 on 2021-10-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimmers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimmer',
            name='preferred_name',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
