# Generated by Django 4.0.4 on 2022-05-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swimmers', '0002_alter_swimmer_preferred_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('stroke', models.CharField(max_length=2)),
                ('course', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('abbreviation', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=45)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('course', models.CharField(choices=[('Y', 'SCY'), ('S', 'SCM'), ('L', 'LCM')], max_length=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='swimmer',
            old_name='gender',
            new_name='sex',
        ),
        migrations.RemoveField(
            model_name='swimmer',
            name='preferred_name',
        ),
        migrations.AddField(
            model_name='swimmer',
            name='pref_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='swimmer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.CreateModel(
            name='OfficialSwim',
            fields=[
                ('official_swim_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimmers.event')),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimmers.meet')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimmers.swimmer')),
            ],
        ),
        migrations.CreateModel(
            name='GroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='swimmers.group')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimmers.swimmer')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='swimmers.season'),
        ),
        migrations.AddField(
            model_name='swimmer',
            name='group',
            field=models.ManyToManyField(through='swimmers.GroupAssignment', to='swimmers.group'),
        ),
    ]
