# Generated by Django 4.0.4 on 2022-06-26 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('stroke', models.CharField(max_length=2)),
                ('course', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('abbreviation', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.group')),
            ],
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=45)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('course', models.CharField(choices=[('Y', 'SCY'), ('S', 'SCM'), ('L', 'LCM')], max_length=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Swimmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('pref_name', models.CharField(blank=True, max_length=45, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(max_length=45)),
                ('sex', models.CharField(max_length=1)),
                ('birthday', models.DateField()),
                ('groups', models.ManyToManyField(through='api.GroupAssignment', to='api.group')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialSwim',
            fields=[
                ('official_swim_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meet')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.swimmer')),
            ],
        ),
        migrations.AddField(
            model_name='groupassignment',
            name='swimmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.swimmer'),
        ),
        migrations.AddField(
            model_name='group',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.season'),
        ),
    ]
